CREATE TABLE IF NOT EXISTS teas (
  ID INTEGER NOT NULL,
  NAME TEXT NOT NULL,
  TEA_CATEGORY_RID INTEGER NOT NULL REFERENCES tea_categories (ID),
  DESCRIPTION TEXT,
  INSTRUCTIONS TEXT,
  RATING INTEGER,
  URL TEXT,
  PRICE NUMERIC (6, 2)
  CONSTRAINT teas_pk PRIMARY KEY (ID)
);

ALTER TABLE TEAS ADD COLUMN IF NOT EXISTS URL TEXT;
ALTER TABLE TEAS ADD COLUMN IF NOT EXISTS PRICE NUMERIC (6, 2);

CREATE SEQUENCE IF NOT EXISTS tea_id_sequence START WITH 1;

DROP TRIGGER IF EXISTS bir_teas ON teas;
DROP FUNCTION IF EXISTS bir_teas();

CREATE FUNCTION bir_teas() RETURNS trigger as $bir_teas$
BEGIN
  IF NEW.id IS NULL THEN
    NEW.id := nextval('tea_id_sequence');
  END IF;
  RETURN NEW;
END;
$bir_teas$ LANGUAGE plpgsql;

CREATE TRIGGER bir_teas BEFORE INSERT ON teas
    FOR EACH ROW EXECUTE PROCEDURE bir_teas();

DROP TRIGGER IF EXISTS bir_tea_purchase_links ON tea_purchase_links;
DROP FUNCTION IF EXISTS bir_tea_purchase_links();
DROP SEQUENCE IF EXISTS tea_puchase_link_id_sequence;
DROP TABLE IF EXISTS tea_purchase_links;
