CREATE TABLE IF NOT EXISTS tea_categories (
  ID INTEGER NOT NULL,
  NAME TEXT NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  CONSTRAINT tea_categories_pk PRIMARY KEY (ID)
);

WITH data AS (
  SELECT 1 AS ID, 'Green' AS NAME, 'Non-oxidized, mild tea' AS DESCRIPTION
   UNION ALL
  SELECT 2 AS ID, 'Black' AS NAME, 'Oxidized tea' AS DESCRIPTION
   UNION ALL
  SELECT 3 AS ID, 'Herbal' AS NAME, 'Not actually tea' AS DESCRIPTION
) INSERT INTO tea_categories (ID, NAME, DESCRIPTION)
SELECT ID, NAME, DESCRIPTION FROM data
ON CONFLICT (ID) DO UPDATE
   SET NAME = EXCLUDED.NAME,
       DESCRIPTION = EXCLUDED.DESCRIPTION;
