CREATE TABLE IF NOT EXISTS users (
  ID INTEGER NOT NULL,
  FIRST_NAME TEXT NOT NULL,
  LAST_NAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  CONSTRAINT users_pk PRIMARY KEY (ID)
);

CREATE SEQUENCE IF NOT EXISTS user_id_sequence START WITH 1;

CREATE TABLE IF NOT EXISTS user_credentials (
  USER_RID INTEGER NOT NULL REFERENCES users (ID),
  PASSWORD TEXT NOT NULL,
  SALT TEXT NOT NULL,
  CONSTRAINT user_credentials_pk PRIMARY KEY (USER_RID)
);
